In [13]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = a.flat[3]
print(b)

4


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Additional excercise

###Create a 2d array, sort the array by a given row

In [23]:
# your code goes here
arr = np.array([
    [1, 2, 3],
    [6, 9, 7],
    [3, 2, 1]
])
print(arr[:, arr[1].argsort()])

[[1 3 2]
 [6 7 9]
 [3 1 2]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Delete a particular row from an array

In [9]:
# your code goes here
a = a[1:]
print(a)

[[4 5 6]]


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 5 by 5 matrix and print the values 1,2,3,4 just below the diagnol

In [12]:


x = np.array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# your code goes here
print(x[1:].diagonal())

[1 2 3 4]


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

